// <auto-generated />
using System;
using System.Collections.Generic;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace _04.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260401065713_FilterCategoryMonthlyMVNullCategory")]
    partial class FilterCategoryMonthlyMVNullCategory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("expense_tracker_backend.Domain.Entities.Budget", b =>
                {
                    b.Property<string>("BudgetId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("budget_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("PeriodType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("period_type");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("total_amount");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("user_id");

                    b.HasKey("BudgetId");

                    b.HasIndex("UserId", "StartDate")
                        .IsUnique()
                        .HasDatabaseName("ix_budgets_user_start");

                    b.ToTable("budgets", (string)null);
                });

            modelBuilder.Entity("expense_tracker_backend.Domain.Entities.BudgetCategory", b =>
                {
                    b.Property<string>("BudgetCategoryId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("budget_category_id");

                    b.Property<decimal>("AlertThreshold")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("alert_threshold");

                    b.Property<decimal>("AllocatedAmount")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("allocated_amount");

                    b.Property<string>("BudgetId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("budget_id");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("BudgetCategoryId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("BudgetId", "CategoryId")
                        .IsUnique()
                        .HasDatabaseName("ix_budget_categories_budget_category");

                    b.ToTable("budget_categories", (string)null);
                });

            modelBuilder.Entity("expense_tracker_backend.Domain.Entities.BudgetSnapshot", b =>
                {
                    b.Property<string>("BudgetCategoryId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("budget_category_id");

                    b.Property<string>("LastTransactionDate")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("last_transaction_date");

                    b.Property<decimal>("SpentAmount")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("spent_amount");

                    b.Property<int>("TransactionCount")
                        .HasColumnType("integer")
                        .HasColumnName("transaction_count");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("BudgetCategoryId");

                    b.ToTable("budget_snapshots", (string)null);
                });

            modelBuilder.Entity("expense_tracker_backend.Domain.Entities.ExpenseCategory", b =>
                {
                    b.Property<string>("CategoryId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category_id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("color");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("icon");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("user_id");

                    b.HasKey("CategoryId");

                    b.HasIndex("UserId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_categories_user_created");

                    b.HasIndex("UserId", "DisplayName")
                        .HasDatabaseName("ix_categories_user_displayname");

                    b.HasIndex("UserId", "Type", "IsActive", "CreatedAt")
                        .IsDescending(false, false, false, true)
                        .HasDatabaseName("ix_categories_user_type_active_created");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("expense_tracker_backend.Domain.Entities.Investment", b =>
                {
                    b.Property<string>("InvestmentId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("investment_id");

                    b.Property<string>("AssetName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("asset_name");

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("asset_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("CurrentPrice")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("current_price");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("image_url");

                    b.Property<string>("MirrorTransactionId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("mirror_transaction_id");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<string>("PortfolioId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("portfolio_id");

                    b.Property<DateOnly>("PurchaseDate")
                        .HasColumnType("date")
                        .HasColumnName("purchase_date");

                    b.Property<decimal>("PurchasePrice")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("purchase_price");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,8)")
                        .HasColumnName("quantity");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("symbol");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("user_id");

                    b.HasKey("InvestmentId");

                    b.HasIndex("PortfolioId");

                    b.HasIndex("UserId", "AssetType")
                        .HasDatabaseName("ix_investments_user_asset_type");

                    b.HasIndex("UserId", "PortfolioId")
                        .HasDatabaseName("ix_investments_user_portfolio");

                    b.HasIndex("UserId", "PurchaseDate")
                        .HasDatabaseName("ix_investments_user_purchase_date");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("ix_investments_user_status");

                    b.ToTable("investments", (string)null);
                });

            modelBuilder.Entity("expense_tracker_backend.Domain.Entities.InvestmentPortfolio", b =>
                {
                    b.Property<string>("PortfolioId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("portfolio_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("user_id");

                    b.HasKey("PortfolioId");

                    b.HasIndex("UserId", "IsActive")
                        .HasDatabaseName("ix_investment_portfolios_user_active");

                    b.ToTable("investment_portfolios", (string)null);
                });

            modelBuilder.Entity("expense_tracker_backend.Domain.Entities.MemberProfile", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("user_id");

                    b.Property<List<string>>("BackUpCodes")
                        .HasColumnType("text[]")
                        .HasColumnName("backup_codes");

                    b.Property<string>("CognitoUserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cognito_user_id");

                    b.Property<string>("CognitoUserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cognito_user_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("currency");

                    b.Property<decimal>("DailyLimit")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("daily_limit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<bool>("MfaEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("mfa_enabled");

                    b.Property<string>("MfaMethod")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("mfa_method");

                    b.Property<string>("PendingEmail")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("pending_email");

                    b.Property<DateTime?>("PendingEmailRequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pending_email_requested_at");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone_number");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_name");

                    b.Property<string>("UserPoolId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_pool_id");

                    b.HasKey("UserId");

                    b.ToTable("member_profiles", (string)null);
                });

            modelBuilder.Entity("expense_tracker_backend.Domain.Entities.RecurringPayment", b =>
                {
                    b.Property<string>("RecurringId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("recurring_id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("amount");

                    b.Property<bool>("AutoPay")
                        .HasColumnType("boolean")
                        .HasColumnName("auto_pay");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("frequency");

                    b.Property<DateTime?>("LastPaidDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_paid_date");

                    b.Property<int>("MissedCount")
                        .HasColumnType("integer")
                        .HasColumnName("missed_count");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTime>("NextDueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_due_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("user_id");

                    b.HasKey("RecurringId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId", "NextDueDate")
                        .HasDatabaseName("ix_recurring_user_nextdue");

                    b.HasIndex("UserId", "Status", "NextDueDate")
                        .HasDatabaseName("ix_recurring_user_status_nextdue");

                    b.ToTable("recurring_payments", (string)null);
                });

            modelBuilder.Entity("expense_tracker_backend.Domain.Entities.SavingGoal", b =>
                {
                    b.Property<string>("SavingGoalId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("saving_goal_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("CurrentAmount")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("current_amount");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("GoalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("goal_name");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("image_url");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<decimal>("TargetAmount")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("target_amount");

                    b.Property<string>("TargetDate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("target_date");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("user_id");

                    b.HasKey("SavingGoalId");

                    b.HasIndex("UserId", "CreatedAt")
                        .HasDatabaseName("ix_saving_goals_user_created");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("ix_saving_goals_user_status");

                    b.ToTable("saving_goals", (string)null);
                });

            modelBuilder.Entity("expense_tracker_backend.Domain.Entities.SavingGoalContribution", b =>
                {
                    b.Property<string>("ContributionId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("contribution_id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("amount");

                    b.Property<string>("ContributionDate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("contribution_date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("MirrorTransactionId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("mirror_transaction_id");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<string>("SavingGoalId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("saving_goal_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("user_id");

                    b.HasKey("ContributionId");

                    b.HasIndex("SavingGoalId", "ContributionDate")
                        .HasDatabaseName("ix_saving_goal_contributions_goal_date");

                    b.HasIndex("UserId", "SavingGoalId")
                        .HasDatabaseName("ix_saving_goal_contributions_user_goal");

                    b.ToTable("saving_goal_contributions", (string)null);
                });

            modelBuilder.Entity("expense_tracker_backend.Domain.Entities.Transaction", b =>
                {
                    b.Property<string>("TransactionId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("transaction_id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("amount");

                    b.Property<string>("CategoryId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("image_url");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("payment_status");

                    b.Property<DateOnly>("TransactionDate")
                        .HasColumnType("date")
                        .HasColumnName("transaction_date");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("user_id");

                    b.HasKey("TransactionId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId", "TransactionDate")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_transactions_user_date");

                    b.HasIndex("UserId", "CategoryId", "TransactionDate")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_transactions_user_category_date");

                    b.HasIndex("UserId", "Type", "Status", "TransactionDate")
                        .IsDescending(false, false, false, true)
                        .HasDatabaseName("ix_transactions_user_type_status_date");

                    b.ToTable("transactions", (string)null);
                });

            modelBuilder.Entity("expense_tracker_backend.Domain.Entities.Budget", b =>
                {
                    b.HasOne("expense_tracker_backend.Domain.Entities.MemberProfile", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("expense_tracker_backend.Domain.Entities.BudgetCategory", b =>
                {
                    b.HasOne("expense_tracker_backend.Domain.Entities.Budget", "Budget")
                        .WithMany("BudgetCategories")
                        .HasForeignKey("BudgetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("expense_tracker_backend.Domain.Entities.ExpenseCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Budget");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("expense_tracker_backend.Domain.Entities.BudgetSnapshot", b =>
                {
                    b.HasOne("expense_tracker_backend.Domain.Entities.BudgetCategory", "BudgetCategory")
                        .WithOne("Snapshot")
                        .HasForeignKey("expense_tracker_backend.Domain.Entities.BudgetSnapshot", "BudgetCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BudgetCategory");
                });

            modelBuilder.Entity("expense_tracker_backend.Domain.Entities.ExpenseCategory", b =>
                {
                    b.HasOne("expense_tracker_backend.Domain.Entities.MemberProfile", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("expense_tracker_backend.Domain.Entities.Investment", b =>
                {
                    b.HasOne("expense_tracker_backend.Domain.Entities.InvestmentPortfolio", "Portfolio")
                        .WithMany("Investments")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("expense_tracker_backend.Domain.Entities.MemberProfile", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Portfolio");

                    b.Navigation("User");
                });

            modelBuilder.Entity("expense_tracker_backend.Domain.Entities.InvestmentPortfolio", b =>
                {
                    b.HasOne("expense_tracker_backend.Domain.Entities.MemberProfile", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("expense_tracker_backend.Domain.Entities.RecurringPayment", b =>
                {
                    b.HasOne("expense_tracker_backend.Domain.Entities.ExpenseCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("expense_tracker_backend.Domain.Entities.MemberProfile", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("expense_tracker_backend.Domain.Entities.SavingGoal", b =>
                {
                    b.HasOne("expense_tracker_backend.Domain.Entities.MemberProfile", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("expense_tracker_backend.Domain.Entities.SavingGoalContribution", b =>
                {
                    b.HasOne("expense_tracker_backend.Domain.Entities.SavingGoal", "SavingGoal")
                        .WithMany("Contributions")
                        .HasForeignKey("SavingGoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SavingGoal");
                });

            modelBuilder.Entity("expense_tracker_backend.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("expense_tracker_backend.Domain.Entities.ExpenseCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("expense_tracker_backend.Domain.Entities.MemberProfile", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("expense_tracker_backend.Domain.Entities.Budget", b =>
                {
                    b.Navigation("BudgetCategories");
                });

            modelBuilder.Entity("expense_tracker_backend.Domain.Entities.BudgetCategory", b =>
                {
                    b.Navigation("Snapshot");
                });

            modelBuilder.Entity("expense_tracker_backend.Domain.Entities.InvestmentPortfolio", b =>
                {
                    b.Navigation("Investments");
                });

            modelBuilder.Entity("expense_tracker_backend.Domain.Entities.SavingGoal", b =>
                {
                    b.Navigation("Contributions");
                });
#pragma warning restore 612, 618
        }
    }
}
